### ISSUE TITLE
Не выполняется запрос

### ISSUE THREAD

**Issue by dronchik** [oleksanderkhomenko/alternative-mongodb-client#2]
Патаюсь выполнить запрос и не могу понять в чем дело и от чего ошибка, название БД и таблицы правильные:
```
$ php index.php
PLEASE ENTER DATABASE NAME: local
PLEAE ENTER SQL: select * from startup_log
Invalid SQLalternative-mongodb-client
```

**Comment by oleksanderkhomenko** [comment]
всі слова типу SELECT FROM, іт.д повинні писатися великими літерами. Так як описано в README.md

**Comment by dronchik** [comment]
Ок, это очень странно, так как ни в одном SQL диалекте, мне не довдилось встречать case sensitive выражения и это реально не очень user friendly. Обычно такие штуки при сравнении опускаются в lowercase и сравниваются с оригинальным варажением и всем удобо и приятно :)

Например я, как супер неадекватные пользователь :) , написал правильный SQL с 3-го раза! 

На да лажно, раз все вышло, решил запустить пепелац, но при это все равно вылезла ошибка:
```
Invalid SQLalternative-mongodb-client $ php index.php
PLEASE ENTER DATABASE NAME: local
PLEAE ENTER SQL: SELECT * from startup_log
Invalid SQLalternative-mongodb-client $ php index.php
PLEASE ENTER DATABASE NAME: local
PLEAE ENTER SQL: select * FROM startup_log
Invalid SQLalternative-mongodb-client $ php index.php
PLEASE ENTER DATABASE NAME: local
PLEAE ENTER SQL: SELECT * FROM startup_log
PHP Fatal error:  Uncaught Error: Class 'Mongo' not found in /Users/andrew/projects/alternative-mongodb-client/index.php:22
Stack trace:
#0 {main}
  thrown in /Users/andrew/projects/alternative-mongodb-client/index.php on line 22

Fatal error: Uncaught Error: Class 'Mongo' not found in /Users/andrew/projects/alternative-mongodb-client/index.php:22
```
Странно, так как до этого все задания нормально запускались и все было ок. Решил проверить наличие extension-а:
```
alternative-mongodb-client $ php -i | grep mongo
Additional .ini files parsed => /usr/local/etc/php/7.0/conf.d/ext-mongodb.ini
mongodb
libmongoc bundled version => 1.5.4
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
mongodb.debug => no value => no value
```
Оказывается все на месте. Но вот потом снова посмотрел в Readme файл и оказалось, что в приложении заюзан deprecated extension https://www.screencast.com/t/xo8bap20s. Тогда все стало на свои места.

Можно это issue не закрывать, дальше я и так все по коду пойму.

Спасибо за оператинвый feedback!

**Comment by oleksanderkhomenko** [comment]
Дякую за feedback. В завданні приклад SQL (4.Структура SQL-я должна быть следующей:) SELECT і т.д. були з великої літери і тому я вирішив що потрібно зробити саме так. 
Я при написанні використовув і deprecated extension і новішу версію , і також через composer php library юзав. Якщо треба - то можу переробити. Зупинився на deprecated тому що думав що вона буде у вас встановлена скоріше за все, але я помилився )

**Comment by dronchik** [comment]
Нет, не стоит на это тратить время. 

Хороший еще вариант, предоставлять несколько способов запуска приложения, как например вот [тут](https://github.com/zendframework/ZendSkeletonApplication) ребята делают. Кроме как классической установки они предлагают вариант запуска приложений через vagrant или docker.

Я последнее время именно docker чаще всего и практикую особенно для запуска сторонних приложений и сервисов, чтобы не "засирать" хостовую машину. Очень хорошо экономит время и так же лешче c CI связать. Кроме этого, вся команда не парится о том, как и где запускать приложение и какие extension-ы ставить.
